# version = "0.0.1"
display:
  # Display control overlays:
  # 3=Artwork only
  # 0=Text overlay displayed
  overlay: 0

  # Display Time Bar:
  # 1=time bar displayed
  # 0=no time bar displayed
  timebar: 1

    # Turn backlight off when mpd state=stop
  # back on when play restarted
  # blank=0 screen will not blank when mpd state=stop
  # blank=n screen will blank after roughly n seconds when mpd state=stop
  blank: 0

  # Add shadow to text
  # Shadow is displayed below and to the right
  # shadow=0 for no shadow text
  # shadow=n : n is the shadow pixel offset
  shadow: 1


